export const dadosDaFatura = {
  awsStorageObjectKey: '',
  chaveDeAcesso: '',
  dataDoVencimento: '',
  dataEmissao: '',
  datasDeLeitura: {
    anterior: '',
    atual: '',
    proxima: '',
  },
  diasUtilizando: '',
  energiaCompensadaGDIEmKWh: {
    quantidade: '',
    precoUnitario: '',
    tarifaUnitaria: '',
    valorTotal: '',
  },
  energiaEletricaEmKWh: {
    quantidade: '',
    precoUnitario: '',
    tarifaUnitaria: '',
    valorTotal: '',
  },
  energiaSCEESemICMSEmKWh: {
    quantidade: '',
    precoUnitario: '',
    tarifaUnitaria: '',
    valorTotal: '',
  },
  endereco: {
    bairro: '',
    cep: '',
    cidade: '',
    complemento: '',
    estado: '',
    numero: '',
    rua: '',
  },
  faturaReferenteA: '',
  linkParaConsulta: '',
  nomeDoCliente: '',
  numeroDaInstalacao: '',
  numeroDaNotaNF: '',
  numeroDoCliente: '',
  valorTotalDaFatura: '',
};

type DadosDaFatura = typeof dadosDaFatura;

export function dataParser(data: DadosDaFatura, awsStorageObjectKey: string) {
  return {
    awsStorageObjectKey,
    chaveDeAcesso: data.chaveDeAcesso,
    dataDoVencimento: data.dataDoVencimento,
    dataEmissao: data.dataEmissao,
    datasDeLeituraAnterior: data.datasDeLeitura.anterior,
    datasDeLeituraAtual: data.datasDeLeitura.atual,
    datasDeLeituraProxima: data.datasDeLeitura.proxima,
    diasUtilizando: data.diasUtilizando,
    energiaCompensadaquantidade: data.energiaCompensadaGDIEmKWh.quantidade,
    energiaCompensadaprecoUnitario:
      data.energiaCompensadaGDIEmKWh.precoUnitario,
    energiaCompensadatarifaUnitaria:
      data.energiaCompensadaGDIEmKWh.tarifaUnitaria,
    energiaCompensadavalorTotal: data.energiaCompensadaGDIEmKWh.valorTotal,
    energiaEletricaquantidade: data.energiaEletricaEmKWh.quantidade,
    energiaEletricaprecoUnitario: data.energiaEletricaEmKWh.precoUnitario,
    energiaEletricatarifaUnitaria: data.energiaEletricaEmKWh.tarifaUnitaria,
    energiaEletricavalorTotal: data.energiaEletricaEmKWh.valorTotal,
    energiaSCEEquantidade: data.energiaSCEESemICMSEmKWh.quantidade,
    energiaSCEEprecoUnitario: data.energiaSCEESemICMSEmKWh.precoUnitario,
    energiaSCEEtarifaUnitaria: data.energiaSCEESemICMSEmKWh.tarifaUnitaria,
    energiaSCEEvalorTotal: data.energiaSCEESemICMSEmKWh.valorTotal,
    bairro: data.endereco.bairro,
    cep: data.endereco.cep,
    cidade: data.endereco.cidade,
    complemento: data.endereco.complemento,
    estado: data.endereco.estado,
    numero: data.endereco.numero,
    rua: data.endereco.rua,
    faturaReferenteA: data.faturaReferenteA,
    linkParaConsulta: data.linkParaConsulta,
    nomeDoCliente: data.nomeDoCliente,
    numeroDaInstalacao: data.numeroDaInstalacao,
    numeroDaNotaNF: data.numeroDaNotaNF,
    numeroDoCliente: data.numeroDoCliente,
    valorTotalDaFatura: data.valorTotalDaFatura,
  };
}
